# Generated by Django 3.1 on 2021-06-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cheater',
            field=models.BooleanField(default=False),
        ),
    ]
