# Generated by Django 3.1 on 2020-09-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_projects', '0003_auto_20200921_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomproject',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
