# Generated by Django 3.1 on 2021-06-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_projects', '0005_weatherproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomproject',
            name='weather',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WeatherProject',
        ),
    ]
