# Generated by Django 3.1 on 2020-09-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200906_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'News'},
        ),
    ]
