# Generated by Django 3.1 on 2020-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200921_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='button_text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
