# Generated by Django 3.1 on 2021-05-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0010_news_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thought',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
