# Generated by Django 3.1 on 2021-06-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210529_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
