# Generated by Django 3.1 on 2020-09-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='MathProject',
        ),
    ]
