# Generated by Django 3.1 on 2020-09-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0002_auto_20200908_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathproject',
            old_name='html_page',
            new_name='pdf_path',
        ),
        migrations.AlterField(
            model_name='mathproject',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='math_pics'),
        ),
    ]
