# Generated by Django 3.1 on 2020-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0003_auto_20200910_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathproject',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
