# Generated by Django 3.1 on 2021-06-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0004_auto_20200921_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathproject',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mathpapers'),
        ),
        migrations.AlterField(
            model_name='mathproject',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='math_pics'),
        ),
    ]
