# Generated by Django 3.1 on 2021-06-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0005_auto_20210619_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathproject',
            name='pdf_path',
        ),
    ]
