# Generated by Django 3.1 on 2020-09-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='defaultGame.png', upload_to='game_pics')),
            ],
        ),
        migrations.CreateModel(
            name='GameVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('html_page', models.CharField(default='', max_length=255)),
                ('goal_game', models.CharField(choices=[('min', 'minimize'), ('max', 'maximize')], default='maximize', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='defaultGame.png', upload_to='game_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('game_variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='games.gamevariant')),
            ],
        ),
    ]
