# Generated by Django 3.1 on 2020-09-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_semiscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semiscore',
            name='token',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
