# Generated by Django 3.1 on 2020-09-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_semiscore_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='short_description',
        ),
        migrations.AddField(
            model_name='game',
            name='how_to',
            field=models.TextField(default='hello world'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
