# Generated by Django 3.1 on 2020-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200916_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gamevariant',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
