# Generated by Django 3.1 on 2020-09-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20200921_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('token', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='cheated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='creation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='exit_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='token',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
