# Generated by Django 3.1 on 2020-09-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20200926_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemiScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('token', models.CharField(default=None, max_length=255)),
                ('used', models.BooleanField(default=False)),
                ('creation_date', models.DateField(blank=True, default=None, null=True)),
                ('exit_date', models.DateField(blank=True, default=None, null=True)),
                ('token_score', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('game_variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='games.gamevariant')),
            ],
        ),
    ]
