# Generated by Django 3.1 on 2020-09-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20200926_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialscore',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='creation_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='exit_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='semiscore',
            name='creation_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='semiscore',
            name='exit_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
