# Generated by Django 3.1 on 2021-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20200926_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevariant',
            name='has_score',
            field=models.BooleanField(default=True),
        ),
    ]
