# Generated by Django 3.1 on 2021-06-19 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gamevariant_has_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnityGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.game')),
                ('zip_windows', models.FileField(blank=True, default=None, upload_to='unity/windows/')),
                ('zip_mac', models.FileField(blank=True, default=None, upload_to='unity/mac/')),
                ('zip_linux', models.FileField(blank=True, default=None, upload_to='unity/linux/')),
            ],
            options={
                'abstract': False,
            },
            bases=('games.game',),
        ),
    ]
