# Generated by Django 3.1 on 2021-06-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_unitygame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitygame',
            name='zip_linux',
            field=models.FileField(blank=True, default=None, null=True, upload_to='unity/linux/'),
        ),
        migrations.AlterField(
            model_name='unitygame',
            name='zip_mac',
            field=models.FileField(blank=True, default=None, null=True, upload_to='unity/mac/'),
        ),
        migrations.AlterField(
            model_name='unitygame',
            name='zip_windows',
            field=models.FileField(blank=True, default=None, null=True, upload_to='unity/windows/'),
        ),
    ]
